receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  awsxray:
  awsemf:
    namespace: Lambda/AWSOTel/Application
    log_group_name: '/aws/lambda/application/metrics'
    dimension_rollup_option: NoDimensionRollup
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      exporters: [awsemf]
